"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os

# Ruta absoluta basada en la ubicación de este archivo settings.py
# configuraciones (parent) -> blog (parent) -> blog (parent) -> raíz
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Agregamos esta lógica para asegurarnos de que encuentre la carpeta static
# Si el BASE_DIR actual no contiene la carpeta 'static', retrocedemos un nivel
if not (BASE_DIR / 'static').exists():
    BASE_DIR = BASE_DIR.parent

print(f"DEBUG: El BASE_DIR corregido es: {BASE_DIR}")


# Verificación extra para el Log de Render
STATIC_FOLDER_PATH = os.path.join(BASE_DIR, 'static')
if os.path.exists(STATIC_FOLDER_PATH):
    print(f"✅ EXITO: Carpeta static encontrada en: {STATIC_FOLDER_PATH}")
else:
    print(f"❌ ERROR: No existe la carpeta static en {STATIC_FOLDER_PATH}")
    # Listamos qué hay ahí para entender qué ve Render
    print(f"DEBUG: Contenido de BASE_DIR: {os.listdir(BASE_DIR)}")



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*l7#4jgy5(o39w)!4iim+x@^&0yp)+7e9db=44pcy*75q$loj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'django.contrib.staticfiles', # Debe ir después de cloudinary
    'apps.posts',
    'apps.nosotras',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/




# --- CONFIGURACIÓN DE ESTÁTICOS (CSS, JS) ---
STATIC_URL = '/static/'
STATIC_ROOT = '/opt/render/project/src/blog/staticfiles'
STATICFILES_DIRS = [
    '/opt/render/project/src/blog/static',
]
# WhiteNoise maneja el CSS
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- CONFIGURACIÓN DE MEDIA (Imágenes de Perfumes) ---
MEDIA_URL = '/media/'
# Importante: Esto le dice a Django que use Cloudinary para los archivos de los modelos
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# --- CLOUDINARY CREDENTIALS ---
# Usamos os.environ para que sea seguro en Render
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'dkyclmyz8'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '456411318782517'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 'GKUeYaRHCmDWdR48DISBazi3zEg')
}